name: by
description: Parlamentsdokumentation Bayerischer Landtag
stealthy: true

publisher:
  type: parliament
  name: Bayerischer Landtag
  url: https://www.bayern.landtag.de
  jurisdiction:
    id: by
    name: Bayern

document_types:
  minor_interpellation: Anfragen\\Schriftliche Anfrage
  major_interpellation: Anfragen\\Interpellation

pipeline:
  init:
    method: dokukratie.operations:init
    params:
      url: https://www.bayern.landtag.de/parlament/dokumente/drucksachen/?dokumentenart=Drucksache&anzahl_treffer=100
      dateformat: "%d.%m.%Y"
      param_names:
        document_type: suchvorgangsart[]
        legislative_term: wahlperiodeid[]
        start_date: erfassungsdatum[start]
        end_date: erfassungsdatum[end]
      document_types:
        - minor_interpellation
        - major_interpellation
      legislative_terms: 18  # earliest: 1, but since 5 more metadata
    handle:
      pass: fetch

  fetch:
    method: memorious_extended.operations:fetch
    handle:
      pass: parse

  parse:
    method: memorious_extended.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - ".//div[@class='row result']//a[text()[contains(., 'Beratungsverlauf')]]"  # detail pages
        - ".//ul[@class='pagination']/li[@class='next']"  # next page
        - ".//table[@id='basisdokument']//a[@class='vorgangDownloadlink'][1]"  # pdf download url
      meta:
        interpellation_raw: ".//table[@id='basisdokument']//span[@class='drucksache']"
        title: ".//table[@id='basisdokument']//span[@class='betreff']"
        originators_raw: ".//table[@id='dokumente']//tbody[@id='dokumente:tb']/tr/td[2]/text()"
    handle:
      fetch: fetch
      store: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
        interpellation_raw: .*\s+(?P<reference>\d{1,2}\/\d+)\s+.*\s+(?P<published_at>\d{2}\.\d{2}\.\d{4}).*
        originators_raw:
          store_as: originators
          split: ","
          patterns: (?P<party>.*)
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      defaults:
        answerers: Staatsregierung
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
