name: by
description: Parlamentsdokumentation Bayerischer Landtag

publisher:
  type: parliament
  name: Bayerischer Landtag
  url: https://www.bayern.landtag.de
  jurisdiction:
    id: by
    name: Bayern

document_types:
  minor_interpellation: Anfragen\\Schriftliche Anfrage
  major_interpellation: Anfragen\\Interpellation

pipeline:
  init:
    method: dokukratie.scrapers.base:init
    params:
      url: https://www.bayern.landtag.de/parlament/dokumente/drucksachen/?dokumentenart=Drucksache&anzahl_treffer=10
      dateformat: "%d.%m.%Y"
      param_names:
        document_type: suchvorgangsart[]
        legislative_term: wahlperiodeid[]
        start_date: erfassungsdatum[start]
        end_date: erfassungsdatum[end]
      document_types:
        - minor_interpellation
        - major_interpellation
      legislative_terms: 18
    handle:
      pass: fetch

  fetch:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: parse

  parse:
    method: dokukratie.scrapers.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - ".//div[@class='row result']//a[text()[contains(., 'Beratungsverlauf')]]"  # detail pages
        - ".//ul[@class='pagination']/li[@class='next']"  # next page
        - ".//table[@id='basisdokument']//a[@class='vorgangDownloadlink'][1]"  # pdf download url
      meta:
        reference: ".//table[@id='basisdokument']//span[@class='drucksache']"
        published_at: ".//table[@id='basisdokument']//span[@class='drucksache']"
        title: ".//table[@id='basisdokument']//span[@class='betreff']"
        originators: ".//table[@id='dokumente']//tbody[@id='dokumente:tb']/tr/td[2]/text()"
    handle:
      fetch: fetch
      store: clean

  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extractors:
        published_at: \d{2}\.\d{2}\.\d{4}
      dateparser:
        dayfirst: true
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
