name: hb
description: Parlamentsdokumentation Bremen (PARIS)

scraper:
  name: starweb
  version: 5.7.00
  url: https://paris.bremische-buergerschaft.de/

publisher:
  type: parliament
  name: Bremische Bürgerschaft
  url: https://bremische-buergerschaft.de
  jurisdiction:
    id: hb
    name: Bremen

document_types:
  minor_interpellation: "KLEINE ANFRAGE UND ANTWORT DES SENATS"
  major_interpellation: "MITTEILUNG DES SENATS (ANTWORT AUF GROẞE ANFRAGEN); MITTEILUNG DES SENATS (ANTWORT AUF  GROẞE ANFRAGE)"

pipeline:

  # emit scrape criteria
  init:
    method: dokukratie.scrapers.starweb:init
    params:
      legislative_terms: 20
      document_types:
        - minor_interpellation
        # - major_interpellation
      dateformat: "%d.%m.%Y"
      url: https://paris.bremische-buergerschaft.de/starweb/paris/servlet.starweb?path=paris/LISSH.web
    handle:
      pass: fetch

  # initialize session
  fetch:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: search

  # perform search via post form
  search:
    method: dokukratie.scrapers.starweb:search
    params:
      fields:
        legislative_term: 12_LISSH_WP
        document_type: 07_LISSH_DTYP
        start_date: 13_LISSH_FASTDATV
        end_date: 14_LISSH_FASTDATB
      formdata:
        __action: 20
        08_LISSH_DART: DRUCKSACHE
        # LimitMaximumHitCount: S32{ITEMS+1:10000000}
        11_LISSH_PARL: L
    handle:
      pass: full_view

  # post form to full view
  full_view:
    method: dokukratie.scrapers.starweb:post
    params:
      formdata:
        __action: 50
        __ReportId: LISSH_BrowseReportHistoryList^0
        LISSH_Browse_ReportFormatList: LISSH_Vorgaenge_Report
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.starweb:parse_results
    params:
      item: './/tbody[@name="RecordRepeater"]/tr'
      download_url: './/td/a[contains(@href, "/dokumente/")]'
      next_page:
        xpath: './/div[@id="seitenzahl"]//span[@name="NextRecsConditional"]'
        formdata:
          __action: 46
      meta:
        title: './/td/h2/a'
        keywords: './/a[@name="ThesaurusLink"]'
        reference: './/div[@class="topic"]/p[@class="info"]'
        originators: './/div[@class="topic"]/p[@class="info"]'
        answerers: './/div[@class="topic"]/p[@class="info"]'
        published_at: './/div[@class="topic"]/p[@class="info"]'
    handle:
      next_page: search
      download: download

  download:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: clean

  # extract & cleanup metadata
  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extractors:
        published_at: \d{2}\.\d{2}\.\d{4}
        originators: .*Antwort\s+(.*)\sund\sAntwort.*
        answerers: .*\sund\sAntwort\s(.+?(?=\s\d)).*
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
