name: hb
description: Parlamentsdokumentation Bremen (PARIS)
stealthy: true

scraper:
  name: starweb
  version: 5.7.00
  url: https://paris.bremische-buergerschaft.de/

publisher:
  type: parliament
  name: Bremische Bürgerschaft
  url: https://bremische-buergerschaft.de
  jurisdiction:
    id: hb
    name: Bremen

document_types:
  minor_interpellation: "KLEINE ANFRAGE UND ANTWORT DES SENATS"
  major_interpellation: "MITTEILUNG DES SENATS (ANTWORT AUF GROẞE ANFRAGEN); MITTEILUNG DES SENATS (ANTWORT AUF  GROẞE ANFRAGE)"

pipeline:

  # emit scrape criteria
  init:
    method: dokukratie.operations:init
    params:
      legislative_terms: 20
      document_types:
        - minor_interpellation
        # - major_interpellation
      dateformat: "%d.%m.%Y"
      url: https://paris.bremische-buergerschaft.de/starweb/paris/servlet.starweb?path=paris/LISSH.web
    handle:
      pass: fetch

  # initialize session
  fetch:
    method: memorious_extended.operations:fetch
    handle:
      pass: search

  # perform search via post form
  search:
    method: dokukratie.scrapers.starweb:search
    params:
      fields:
        legislative_term: 12_LISSH_WP
        document_type: 07_LISSH_DTYP
        start_date: 13_LISSH_FASTDATV
        end_date: 14_LISSH_FASTDATB
      formdata:
        __action: 20
        08_LISSH_DART: DRUCKSACHE
        # NumPerSegment: 100000
        # LimitMaximumHitCount: "S32{ITEMS+1:10000000}"
        11_LISSH_PARL: L  # only Landtag
    handle:
      pass: full_view

  # post form to full view
  full_view:
    method: memorious_extended.operations:post_form
    params:
      form: './/form[@name="__form"]'
      data:
        __action: 50
        __ReportId: LISSH_BrowseReportHistoryList^0
        LISSH_Browse_ReportFormatList: LISSH_Vorgaenge_Report
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.starweb:parse_results
    params:
      item: './/tbody[@name="RecordRepeater"]'
      download_url: './/td/a[contains(@href, "/dokumente/")][last()]/@href'
      next_page:
        xpath: './/div[@id="seitenzahl"]//span[@name="NextRecsConditional"]'
        formdata:
          __action: 46
      meta:
        title: './/tr[@name="Repeat_WHET"]/td/h2'
        keywords: './/a[@name="ThesaurusLink"]'
        summary: './/tr[@name="Repeat_HA"]/td[2]'
        meta_raw: './/tr[@name="Repeat_Fund"]/td[3]'
    handle:
      next_page: search
      pass: download

  download:
    method: memorious_extended.operations:fetch
    handle:
      pass: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
      meta_raw: Drs\s+(?P<interpellation_reference>\d{1,2}\/\d+)\s+.*\s+Anfrage\s+vom\s+(?P<interpellation_date>\d{2}\.\d{2}\.\d{4}),\s+Urheber:\s+(?P<originators_raw>.*)\s+Drs\s+(?P<reference>\d{1,2}\/\d+)\s+.*\s+(?P<published_at>\d{2}\.\d{2}\.\d{4})(,\s+Urheber:\s+(?P<answerers>.*))?
      originators_raw:
        store_as: originators
        split: ","
        patterns: (?P<party>.*)
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
