name: he
description: Parlamentsdatenbank Hessen
stealthy: true

publisher:
  type: parliament
  name: Hessischer Landtag
  url: https://hessischer-landtag.de/
  jurisdiction:
    id: he
    name: Hessen

scraper:
  name: starweb
  version: 5.9.1
  url: http://starweb.hessen.de/starweb/LIS/servlet.starweb

document_types:
  major_interpellation: GROßE ANFRAGE
  minor_interpellation: KLEINE ANFRAGE

pipeline:

  init:
    method: dokukratie.operations:init
    params:
      legislative_terms: WP20  # FIXME
      document_types:
        - minor_interpellation
        - major_interpellation
      url: http://starweb.hessen.de/starweb/LIS/servlet.starweb?path=LIS/PdPi.web
    handle:
      pass: fetch

  # initialize session
  fetch:
    method: memorious_extended.operations:fetch
    handle:
      pass: search

  search:
    method: dokukratie.scrapers.starweb:search
    params:
      fields:
        legislative_term: WPDatabase
        document_type: dokumenttyp
        start_date: zeitraum_von
        end_date: zeitraum_bis
      formdata:
        __action: 69
        status: X  # erledigt
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.starweb:parse_results
    params:
      item: './/tbody[@starweb_type="Record Repeater"]'
      detail_url: http://starweb.hessen.de/starweb/LIS/servlet.starweb?path=LIS/PdPi_FLMore20.web
      detail_params: './/span[@name="OFR_Betreff"]/a/@onclick'
      next_page:
        xpath: './/span[@name="NextRecsConditional"]'
        formdata:
          __action: 262
      meta:
        title: './/span[@name="OFR_Betreff"]'
        reference:  './/span[@name="OFR_Drs"]'
        originators_raw: './/span[@name="OFR_Initiator"]'
    handle:
      next_page: search
      pass: fetch_detail

  fetch_detail:
    method: memorious_extended.operations:fetch
    handle:
      pass: parse_detail

  parse_detail:
    method: memorious_extended.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
          - './/table[@id="listTable"]//pre/text()[contains(., "Drucksache")][last()]/following-sibling::a[1]'  # link to pdf download page
          - './/a[contains(text(), "Originaldokument als PDF-Datei")]'  # actual link to pdf
      meta:
        meta_raw: './/table[@id="listTable"]//pre/text()[contains(., "Drucksache")]'
    handle:
      fetch: fetch_detail
      store: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
      meta_raw: (?P<summary>.*)\s+Kleine\s+Anfrage\s+(?P<originators_raw>.*)\s+(?P<interpellation_date>\d{2}\.\d{2}\.\d{4})\s+und\s+Antwort\s+(?P<published_at>\d{2}\.\d{2}\.\d{4}).*
      originators_raw:
        store_as: originators
        split: ";"
        patterns:
          - (\s+)?(?P<name>.*),\s+(?P<party>[\w\s]+)(\s+)?$
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      defaults:
        answerers: Landesregierung
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
