name: mv
description: Parlamentsdokumentation Mecklenburg-Vorpommern

publisher:
  type: parliament
  name: Landtag Mecklenburg-Vorpommern
  url: https://landtag-mv.de/
  jurisdiction:
    id: mv
    name: Mecklenburg-Vorpommern

document_types:
  major_interpellation: 163  # Große Anfrage
  minor_interpellation: 136  # Kleine Anfrage

scraper:
  name: parldok
  version: 5.6.0
  url: https://www.dokumentation.landtag-mv.de/parldok/formalkriterien/

pipeline:
  init:
    method: dokukratie.scrapers.parldok:init
    params:
      legislative_terms: 7
      document_types:
        - minor_interpellation
        - major_interpellation
      dateformat: "%d.%m.%Y"
    handle:
      pass: search

  search:
    method: dokukratie.scrapers.parldok:search
    handle:
      pass: fetch_results

  fetch_results:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.parldok:parse_results
    params:
      item: './/button[@class="parldokresult-vorgang"]/../..'
      detail_url: './/button/@onclick'
      next_page: './/div[@class="pd_resultnavigation"]/a/@href'
      meta:
        reference: 'preceding-sibling::tr/td[@headers="result-nummer"]/text()'
        interpellation_raw: './/td[@headers="result-urheber"]/text()'
        published_at: 'preceding-sibling::tr/td[@headers="result-datum"]/text()'
    handle:
      next_page: fetch_results
      fetch: fetch_detail

  fetch_detail:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: parse_detail

  parse_detail:
    method: dokukratie.scrapers.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - ".//div[@class='element-vorgang']"
      meta:
        title: ".//div[@id='content']/fieldset/table/tbody/tr[2]/td[2]"
        summary: ".//div[@id='content']/fieldset/table/tbody/tr[3]/td[2]"
        keywords: ".//div[@id='content']/fieldset/table/tbody/tr[1]/td[2]"
    handle:
      fetch: fetch_detail
      store: clean

  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extract:
        interpellation_raw: (?P<originators_raw>.*),\s+Landesregierung\s+\((?P<answerers>.*)\).*
      parse:
        originators:
          source: originators_raw
          split: ","
          patterns:
            - (?P<name>.*)\s+\((?P<party>.*)\)
            - \((?P<party>.*)\)
            - (?P<party>.*)\)
            - \((?P<party>.*)
            - (?P<party>.*)
      dateparser:
        dayfirst: true
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
