name: mv
description: Parlamentsdokumentation Mecklenburg-Vorpommern
stealthy: true

publisher:
  type: parliament
  name: Landtag Mecklenburg-Vorpommern
  url: https://landtag-mv.de/
  jurisdiction:
    id: mv
    name: Mecklenburg-Vorpommern

document_types:
  major_interpellation: 163  # Große Anfrage
  minor_interpellation: 136  # Kleine Anfrage

scraper:
  name: parldok
  version: 5.6.0
  url: https://www.dokumentation.landtag-mv.de/parldok/formalkriterien/

pipeline:
  init:
    method: dokukratie.operations:init
    params:
      legislative_terms: 7
      document_types:
        - minor_interpellation
        - major_interpellation
      dateformat: "%d.%m.%Y"
    handle:
      pass: search

  search:
    method: memorious_extended.operations:post
    params:
      url: https://www.dokumentation.landtag-mv.de/parldok/formalkriterien/
      use_data:
        DokumententypId: document_type
        LegislaturperiodenNummer: legislative_term
        DatumVon: start_date
        DatumBis: end_date
    handle:
      pass: fetch_results

  fetch_results:
    method: memorious_extended.operations:fetch
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.parldok:parse_results
    params:
      item: './/button[@class="parldokresult-vorgang"]/../..'
      detail_url: './/button/@onclick'
      next_page: './/div[@class="pd_resultnavigation"]/a/@href'
      meta:
        reference: 'preceding-sibling::tr/td[@headers="result-nummer"]/text()'
        interpellation_raw: './/td[@headers="result-urheber"]/text()'
        published_at: 'preceding-sibling::tr/td[@headers="result-datum"]/text()'
    handle:
      next_page: fetch_results
      fetch: fetch_detail

  fetch_detail:
    method: memorious_extended.operations:fetch
    handle:
      pass: parse_detail

  parse_detail:
    method: memorious_extended.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - ".//div[@class='element-vorgang']"
      meta:
        title: ".//div[@id='content']/fieldset/table/tbody/tr[2]/td[2]"
        summary: ".//div[@id='content']/fieldset/table/tbody/tr[3]/td[2]"
        keywords: ".//div[@id='content']/fieldset/table/tbody/tr[1]/td[2]"
    handle:
      fetch: fetch_detail
      store: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
      interpellation_raw: (?P<originators_raw>.*),\s+Landesregierung\s+\((?P<answerers>.*)\).*
      originators_raw:
        store_as: originators
        split: ","
        patterns:
          - (?P<name>.*)\s+\((?P<party>.*)\)
          - \((?P<party>.*)\)
          - (?P<party>.*)\)
          - \((?P<party>.*)
          - (?P<party>.*)
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
