name: ni
description: Niedersächsisches Landtagsdokumentationssystem
state: ni

publisher:
  type: parliament
  name: Landtag Niedersachsen
  url: https://www.landtag-niedersachsen.de/
  jurisdiction:
    id: ni
    name: Niedersachsen

scraper:
  name: starweb
  version: 6.0.01
  url: https://www.nilas.niedersachsen.de/starweb/NILAS/start.html

document_types:
  major_interpellation: Große Anfrage Mit Antwort
  minor_interpellation: Kleine Anfrage Zur Schriftlichen Beantwortung Mit Antwort

pipeline:

  init:
    method: dokukratie.scrapers.starweb:init
    params:
      legislative_terms: 18
      document_types:
        - minor_interpellation
        - major_interpellation
      url: https://www.nilas.niedersachsen.de/starweb/NILAS/servlet.starweb?path=NILAS/lissh.web
      dateformat: "%d.%m.%Y"
    handle:
      pass: fetch

  # initialize session
  fetch:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: search

  search:
    method: dokukratie.scrapers.starweb:search
    params:
      fields:
        legislative_term: wplist
        document_type: Suchzeile6
        start_date: Suchzeile7
        end_date: Suchzeile8
      formdata:
        __action: 5
        Suchzeile5: DRUCKSACHE
        # maxtrefferlist1: S32{ITEMS+1:100000000}
        # ReportFormatListDisplay: Vollanzeige
    handle:
      pass: full_view


  # post form to full view
  full_view:
    method: dokukratie.scrapers.starweb:post
    params:
      formdata:
        __action: 28
        ReportFormatListDisplay: Vorgaenge
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.starweb:parse_results
    params:
      item: './/table[@id="listTable"]//ul[@class="fundstelle"]/..'
      download_url: './/ul[@class="fundstelle"]/li[contains(text(), "Drucksache")][last()]/a/@href'
      meta:
        title: ".//b/text()"
        summary: ".//b/../following-sibling::p[1]/text()"
        reference: './/ul[@class="fundstelle"]/li[contains(text(), "Drucksache")][last()]/a'
        keywords: './/a[@name="ThesaurusLink"]'
        published_at: './/ul[@class="fundstelle"]/li[contains(text(), "Drucksache")][last()]'
        answerers: './/ul[@class="fundstelle"]/li[contains(text(), "Drucksache")][last()]'
        originators: './/ul[@class="fundstelle"]/li[contains(text(), "Drucksache")][1]'
    handle:
      next_page: search
      pass: download

  download:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: clean

  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      dateparser:
        dayfirst: true
      extractors:
        published_at: \d{2}\.\d{2}\.\d{4}
        originators:
          - (Kleine|Große)\s+Anfrage(?:\s+zur\s+.*\s+Beantwortung)?\s+(?P<originators>.+)\s+\d+\.
          - (Kleine|Große)\s+Anfrage\s+mit\s+Antwort\s+(?P<originators>.+)\s+\d+\.
        answerers:
          - (?:Ergänzung)?\s?Antwort\s+(?P<answerers>[^\d]+)\s+(\d+\.\d+\.\d+)
          - (Kleine|Große)\s+Anfrage(?:\s+zur\s+.*\s+Beantwortung)\s+mit\s+Antwort\s+(?P<originators>.+)\s+\d+\.
      parser:
        originators:
          split: ","
          pattern: (?P<name>.*)\((?P<party>.*)\)
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
