name: nw
description: Parlamentsdatenbank Nordrhein-Westfalen

publisher:
  type: parliament
  name: Landtag NRW
  url: https://www.landtag.nrw.de
  jurisdiction:
    id: nw
    name: Nordrhein-Westfalen

document_types:
  major_interpellation: GROßE ANFRAGE
  minor_interpellation: KLEINE ANFRAGE

pipeline:

  init:
    method: dokukratie.scrapers.operations:init
    params:
      url: "https://www.landtag.nrw.de/home/dokumente/dokumentensuche/parlamentsdokumente/parlamentsdatenbank-suchergebnis.html"
      dateformat: "%d.%m.%Y"
      urlparams:
        dokart: DRUCKSACHE
      legislative_terms: 17
      document_types:
        - minor_interpellation
        - major_interpellation
      param_names:
        document_type: doktyp
        legislative_term: wp
        start_date: dokdatumvon
        end_date: dokdatumbis
    handle:
      pass: fetch

  fetch:
    method: dokukratie.scrapers.operations:fetch
    params:
      skip_incremental:
        urlpattern: .*view=berver$
    handle:
      pass: parse

  parse:
    method: dokukratie.scrapers.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - './/a[@data-js-page="next"]'  # next pages
        - ".//a/span[contains(text(), 'Beratungsverlauf')]/.."  # detail page
        - './/article[@class="e-search-result"]//p[contains(text(), "Antwort")]' # pdf url on detail page
      meta:
        # on detail page
        reference: ".//p[contains(text(), 'Antwort')]/a/text()"
        title: './/div[@class="e-search-result__body"]/p/strong/b'
        interpellation_raw: './/div[@class="e-search-result__body"]/p[1]'
        answer_raw: './/div[@class="e-search-result__body"]/p[2]'
    handle:
      fetch: fetch
      store: clean

  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extract:
        interpellation_raw: .*\s+(Kleine\s+Anfrage|KlAnfr)\s+\d+\s+(?P<originators_raw>.*)\s+(Drucksache|Drs)\s+(?P<interpellation_reference>\d{1,2}\/\d+)\s+(?P<interpellation_date>\d{2}\.\d{2}\.\d{4}).*
        answer_raw: Antwort\s+(?P<answerers>.*)\s+Drucksache\s+\d{1,2}\/\d+\s+(?P<published_at>\d{2}\.\d{2}\.\d{4}).*
      parse:
        originators:
          source: originators_raw
          split: ";"
          patterns:
            - (?P<name>.*)
      dateparser:
        dayfirst: true
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
