name: nw
description: Parlamentsdatenbank Nordrhein-Westfalen
stealthy: true

publisher:
  type: parliament
  name: Landtag NRW
  url: https://www.landtag.nrw.de
  jurisdiction:
    id: nw
    name: Nordrhein-Westfalen

document_types:
  major_interpellation: GROßE ANFRAGE
  minor_interpellation: KLEINE ANFRAGE

pipeline:

  init:
    method: dokukratie.operations:init
    params:
      url: "https://www.landtag.nrw.de/home/dokumente/dokumentensuche/parlamentsdokumente/parlamentsdatenbank-suchergebnis.html"
      dateformat: "%d.%m.%Y"
      urlparams:
        dokart: DRUCKSACHE
      legislative_terms: 17
      document_types:
        - minor_interpellation
        - major_interpellation
      param_names:
        document_type: doktyp
        legislative_term: wp
        start_date: dokdatumvon
        end_date: dokdatumbis
    handle:
      pass: fetch

  fetch:
    method: memorious_extended.operations:fetch
    params:
      skip_incremental:
        urlpattern: .*view=berver$
    handle:
      pass: parse

  parse:
    method: memorious_extended.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - './/a[@data-js-page="next"]'  # next pages
        - ".//a/span[contains(text(), 'Beratungsverlauf')]/.."  # detail page
        - './/article[@class="e-search-result"]//p[contains(text(), "Antwort")]' # pdf url on detail page
      meta:
        # on detail page
        reference: ".//p[contains(text(), 'Antwort')]/a/text()"
        title: './/div[@class="e-search-result__body"]/p/strong/b'
        interpellation_raw: './/div[@class="e-search-result__body"]/p[1]'
        answer_raw: './/div[@class="e-search-result__body"]/p[2]'
    handle:
      fetch: fetch
      store: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
        interpellation_raw: .*\s+(Kleine\s+Anfrage|KlAnfr|Große\s+Anfrage|GrAnfr)\s+\d+\s+(?P<originators_raw>.*)\s+(Drucksache|Drs)\s+(?P<interpellation_reference>\d{1,2}\/\d+)\s+(?P<interpellation_date>\d{2}\.\d{2}\.\d{4}).*
        answer_raw: Antwort\s+(?P<answerers>.*)\s+(Drucksache|Drs)\s+\d{1,2}\/\d+\s+(?P<published_at>\d{2}\.\d{2}\.\d{4}).*
        originators_raw:
          store_as: originators
          split: " , "  #  Weske, Markus Herbert SPD , Paul, Josefine; Müller, Thomas GRÜNE
          patterns:
            - (?P<names>.*)\s+(?P<party>\w+)(\s+)?$
          originators_all:
            split: ";"
            patterns:
              - (?P<name>.*)
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
