name: parlamentsspiegel
description: Parlamentsspiegel

document_types:
  interpellation: ANFRAGE

publisher:
  type: aggregator
  name: Parlamentsspiegel
  url: https://www.parlamentsspiegel.de
  jurisdiction:
    id: de
    name: Deutschland

pipeline:
  init:
    method: dokukratie.scrapers.operations:init
    params:
      url: https://www.parlamentsspiegel.de/home/suchergebnisseparlamentsspiegel.html?view=kurz&sortierung=dat_desc
      document_types: interpellation
      dateformat: "%d.%m.%Y"
      param_names:
        document_type: vorgangstyp
        start_date: datumVon
        end_date: datumBis
    handle:
      pass: fetch

  fetch:
    method: dokukratie.scrapers.operations:fetch
    params:
      skip_incremental:
        key:
          urlpattern: .*view=einzel.*
        target:
          stage: store
    handle:
      pass: parse

  parse:
    method: dokukratie.scrapers.operations:parse
    params:
      store:
        mime_group: documents
      include_paths:
        - './/ul[@class="paging"]/li[@class="next"]'  # next pages
        - './/dd[@class="link"]/a[@class="beratungsstand"]/..'  # detail page
        - './/table//a/img[@alt="Dokument anzeigen"]/../..'  # external download url
        - './/iframe'
      meta:
        # on detail page
        title: ".//table/tr[2]/td[2]/text()[1]"
        reference: '(.//table/tr/td[contains(text(), "Drucksache")])[last()]/text()'
        published_at: '(.//table/tr/td[contains(text(), "Drucksache")])[last()]/text()'
        state: '(.//table/tr/td[contains(text(), "Drucksache")])[1]/text()'
        meta_info: ".//table/tr[3]/td[2]/text()"
        source_url: './/a[contains(text(),"Kurzansicht")]/@href'
        summary: ".//table/tr[2]/td[2]"
        document_type: '(.//table/tr/td[contains(text(), "Anfrage")])[1]/text()'
    handle:
      fetch: fetch
      store: clean

  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extractors:
        published_at: \d{2}\.\d{2}\.\d{4}
        state: ([\w-]+)\s?
        document_type: .[\w-]+\s?-?([\w\s]+)
      values:
        state:
          "Bayerischer": by
          "Berlin": be
          "Brandenburg": bb
          "Hamburg": hh
          "Hessen": he
          "Mecklenburg-Vorpommern": mv
          "Niedersachsen": ni
          "NW": nw
          "Rheinland-Pfalz": rp
          "Sachsen-Anhalt": st
          "Schleswig-Holstein": sh
          "Thüringen": th
      dateparser:
        dayfirst: true
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
