name: rp
description: OPAL Rheinland-Pfalz

publisher:
  type: parliament
  name: Landtag Rheinland-Pfalz
  url: https://www.landtag.rlp.de
  jurisdiction:
    id: rp
    name: Rheinland-Pfalz

scraper:
  name: starweb
  version: 6.0.01
  url: https://opal.rlp.de/starweb/OPAL_extern/index.htm

document_types:
  major_interpellation: GROßE ANFRAGE
  minor_interpellation: KLEINE ANFRAGE UND ANTWORT; ANTWORT

pipeline:

  init:
    method: dokukratie.scrapers.starweb:init
    params:
      legislative_terms: 18
      document_types:
        - minor_interpellation
        - major_interpellation
      url: https://opal.rlp.de/starweb/OPAL_extern/servlet.starweb?path=OPAL_extern/PDOKU.web
    handle:
      pass: fetch

  # initialize session
  fetch:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: search

  search:
    method: dokukratie.scrapers.starweb:search
    params:
      fields:
        legislative_term: 02_PDOKU_WP
        document_type: 05_PDOKU_DTYP
      formdata:
        __action: 21
        03_PDOKU_DART: D
        18_PDOKU_Anfrage: DBESUP="DTYPF=ANTWORT"  # only with answers
        # LimitMaximumHitCount: S99{ITEMS+1:10000000}
    handle:
      pass: parse_results

  parse_results:
    method: dokukratie.scrapers.starweb:parse_results
    params:
      item: './/tbody[@name="RecordRepeater"]'
      download_url: './/tr[@name="Repeat_Fund"]//div[@class="fundstelle"]//a[@title="Gesamtdokument"]/@href'
      next_page:
        xpath: './/div[@id="seitenzahl"]//span[@name="NextRecsConditional"]'
        formdata:
          __action: 52
      meta:
        # reference, originators, etc..: store the full paragraph for each field,
        # extract the granular information later in `clean` stage
        title: './/tr[@name="Repeat_WHET"]/td/b'
        keywords: './/a[@name="ThesaurusLink"]/text()'
        reference:  './/tr[@name="Repeat_Fund"]//div[@class="fundstelle"]/div[@class="morefund"]'
        originators: './/tr[@name="Repeat_Fund"]//div[@class="fundstelle"]/div[@class="morefund"]'
        answerers: './/tr[@name="Repeat_Fund"]//div[@class="fundstelle"]/div[@class="morefund"]'
        published_at: './/tr[@name="Repeat_Fund"]//div[@class="fundstelle"]/div[@class="morefund"]'
    handle:
      next_page: search
      pass: download

  download:
    method: dokukratie.scrapers.operations:fetch
    handle:
      pass: clean

  # extract & cleanup metadata
  clean:
    method: dokukratie.scrapers.operations:clean
    params:
      extractors:
        published_at: \d{2}\.\d{2}\.\d{4}
        originators: Kleine\s+Anfrage\s+[\d\s]+(.+?)\s+und
        answerers: .*\s+und\s+Antwort\s+(.+?)\s
      dateparser:
        dayfirst: true
    handle:
      pass: store

  store:
    method: dokukratie.scrapers.operations:store
