name: sn
description: Parlamentsdokumentation EDAS Sachsen
stealthy: true

document_types:
  minor_interpellation: KlAnfr
  major_interpellation: GrAnfr

publisher:
  type: parliament
  name: Sächsischer Landtag
  url: https://www.landtag.sachsen.de/de
  jurisdiction:
    id: sn
    name: Sachsen

scraper:
  url: https://edas.landtag.sachsen.de

pipeline:
  # emit scrape criteria
  init:
    method: dokukratie.operations:init
    params:
      url: https://edas.landtag.sachsen.de
      document_types:
        - minor_interpellation
      legislative_terms: 7
    handle:
      pass: init_session

  # init session cookie
  init_session:
    method: memorious_extended.operations:fetch
    handle:
      pass: init_form

  # this form page only works with correct referer:
  init_form:
    method: memorious_extended.operations:fetch
    params:
      url: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/suchmaske_einfach.aspx
      headers:
        Referer: https://edas.landtag.sachsen.de/Header.htm
    handle:
      # pass: redirect
      pass: search

  # redirect to legislative term
  # redirect:
  #   method: memorious_extended.operations:fetch
  #   params:
  #     headers:
  #       Referer: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/suchmaske_einfach.aspx
  #     rewrite:
  #       method: template
  #       data: /redirect.aspx?wahlperiode={{ legislative_term }}
  #   handle:
  #     pass: search

  search:
    method: memorious_extended.operations:post_form
    params:
      form: './/form[@id="aspnetForm"]'
      data:
        __CALLBACKID: ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback
        __CALLBACKPARAM: "c0:"
        #   __EVENTARGUMENT: Click
        #   __EVENTTARGET: ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback$btn_EinfSuche
        ctl00_masterContentCallback_content_suchmaske_tblSearch_tabSuche_panelUmSuchmaskeEinfach_suchmaskeEinfachCallback_sb_EinfDokartSuchmaskeElement_ec_VI: Drs
        ctl00_masterContentCallback_content_suchmaske_tblSearch_tabSuche_panelUmSuchmaskeEinfach_suchmaskeEinfachCallback_sb_EinfDoktyp_ec_VI: KlAnfr
        ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback$sb_EinfDoktyp$ec$DDD$L: KlAnfr
        ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback$sb_EinfDoktyp$ec: KlAnfr - Kleine Anfrage
        # ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback$tf_EinfDoknrVon$ec: 1
        # ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSuche$panelUmSuchmaskeEinfach$suchmaskeEinfachCallback$tf_EinfDoknrBis$ec: 1000
        ctl00_masterContentCallback_content_suchmaske_tblSearch_tabSuche_panelUmSuchmaskeEinfach_suchmaskeEinfachCallback_sb_EinfOrderBy_logisch_ec_VI: Eingangsdatum_desc
        # ctl00_masterContentCallback_content_suchmaske_tblSearch_tabSucheErweitert_panelUmSuchmaskeErweitert_suchmaskeErweitertCallback_sb_ExpBehandlungsstand_ec_VI: Antw
        # ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSucheErweitert$panelUmSuchmaskeErweitert$suchmaskeErweitertCallback$sb_ExpBehandlungsstand$ec: "Antw -  "
        # ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSucheErweitert$panelUmSuchmaskeErweitert$suchmaskeErweitertCallback$sb_ExpBehandlungsstand$ec$DDD$L: Antw
      use_data:
        ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSucheErweitert$panelUmSuchmaskeErweitert$suchmaskeErweitertCallback$tf_ExpEingdatumVon$ec: start_date
        ctl00$masterContentCallback$content$suchmaske$tblSearch$tabSucheErweitert$panelUmSuchmaskeErweitert$suchmaskeErweitertCallback$tf_ExpEingdatumBis$ec: end_date
      headers:
        Referer: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/suchmaske_einfach.aspx
    handle:
      pass: fetch_results

  # result list is created for the current session by the previous post request
  fetch_results:
    method: memorious_extended.operations:fetch
    params:
      test_loops: 5
      url: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/trefferliste.aspx?NavSeite=1
      pagination:
        param: NavSeite
      headers:
        Referer: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/suchmaske_einfach.aspx
    handle:
      pass: parse_results

  # parse result list and yield data for each item
  parse_results:
    method: memorious_extended.operations:parse_listing
    params:
      test_loops: 5
      parse_html: false
      emit: true
      items: './/td[@class="dxdvItem_EDAS dx-al"]'
      meta:
        reference: './/td[@class="text"]/a[contains(text(), "Drs")]'
        dok_nr: './/td[@class="text"]/a[contains(text(), "Drs")]'
        title: './/td[@class="text"]/b'
      pagination:
        total: './/input[@id="ctl00_masterContentCallback_content_tf_AnzahlBis_ec_I"]/@value'
        per_page: 20
    handle:
      next_page: fetch_results  # pagination
      item: extract_dok_nr

  # extract `dok_nr` via regex to use in url template for next fetch stage
  extract_dok_nr:
    method: memorious_extended.operations:regex_groups
    params:
      dok_nr: .*\/(?P<dok_nr>\d+)\s*$
      reference: .*\s+(?P<reference>\d{1,2}\/\d+)
    handle:
      pass: fetch_detail

  # generate url from current data and fetch detail page
  fetch_detail:
    method: memorious_extended.operations:fetch
    params:
      headers:
        Referer: https://edas.landtag.sachsen.de/parlamentsdokumentation/parlamentsarchiv/suchmaske_einfach.aspx
      rewrite:
        method: template
        data: /parlamentsdokumentation/parlamentsarchiv/treffer_vorgang.aspx?VorgangButton=y&dok_art=Drs&leg_per={{ legislative_term }}&refferer=&index=11&dok_nr={{ dok_nr }}
    handle:
      pass: parse_detail

  parse_detail:
    method: memorious_extended.operations:parse
    params:
      parse_html: false
      emit: true
      meta:
        interpellation_raw: "(.//a[contains(@href, 'showDocumentByID')]//text())[1]"
        answer_raw: "(.//a[contains(@href, 'showDocumentByID')]//text())[2]"
        dok_id: "(.//a[contains(@href, 'showDocumentByID')]/@href)[2]"
    handle:
      pass: extract_dok_id

  # extract `dok_id` via regex to use in url template for next fetch stage
  extract_dok_id:
    method: memorious_extended.operations:regex_groups
    params:
      dok_id: .*\s+(?P<dok_id>\d+)\)
    handle:
      pass: fetch_viewer

  fetch_viewer:
    method: memorious_extended.operations:fetch
    params:
      rewrite:
        method: template
        data: /viewer/viewer_navigation.aspx?dok_nr={{ dok_nr }}&dok_art=Drs&leg_per={{ legislative_term }}&pos_dok=&dok_id={{ dok_id }}
    handle:
      pass: parse_viewer

  parse_viewer:
    method: memorious_extended.operations:parse
    params:
      parse_html: false
      emit: true
      meta:
        url: './/body/@onload'
    handle:
      pass: extract_url

  # extract url via regex
  extract_url:
    method: memorious_extended.operations:regex_groups
    params:
        url: .*(?P<url>https.*\.pdf).*
    handle:
      pass: download

  download:
    method: memorious_extended.operations:fetch
    handle:
      pass: extract

  extract:
    method: memorious_extended.operations:regex_groups
    params:
      interpellation_raw:
        # not answered
        - .*KlAnfr\s+(?P<originators_raw>.*)\s+(?P<published_at>\d{2}\.\d{2}\.\d{4})\s+Drs\s+(?P<reference>\d{1,2}\/\d+)$
        # answered
        - .*KlAnfr\s+(?P<originators_raw>.*)\s+(?P<interpellation_date>[\d\.]+)\s+Drs\s+(?P<interpellation_reference>[\d\/]+)
      answer_raw: .*Antw\s+(?P<answerers>.*)\s+(?P<published_at>[\d\.]+)\s+Drs\s+(?P<reference>[\d\/]+)
      originators_raw:
        store_as: originators
        split: ","
        patterns: (?P<name>.*)  # FIXME
    handle:
      pass: clean

  # clean and validate metadata
  clean:
    method: dokukratie.operations:clean
    params:
      defaults:
        answerers: not answered  # FIXME
      values:
        foreign_id: "{publisher[jurisdiction][id]}-{reference}"
      required:
        - legislative_term
        - document_type
        - reference
        - foreign_id
        - title
        - originators
        - answerers
        - published_at
        - publisher
      typing:
        ignore:
          - modified_at
          - retrieved_at
          - reference
          - interpellation_reference
        dateparserkwargs:
          dayfirst: true
      drop:
        - page
        - formdata
    handle:
      pass: store

  store:
    method: memorious_extended.operations:store
